name: Vanilla OS Driftwm
id: custom # Replace this ID with your image ID
vibversion: 1.0.7

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
    addincludes: true
    singlelayer: false
    labels:
      maintainer: self-maintained # Optionally, Replace this with your name
    args:
      DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive

    # Commands to run first before building the modules
    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Put your custom actions below this comment

      - name: install-dependencies
        type: apt
        sources:
          - packages:
              # --- Dépendances DriftWM (Base Wayland/Smithay) ---
              - libseat-dev
              - libdisplay-info-dev
              - libinput-dev
              - libudev-dev
              - libgbm-dev
              - libxkbcommon-dev
              - libwayland-dev
              - libpam0g-dev
              
              # --- Outils de compilation globaux ---
              - build-essential
              - git
              - curl
              - pkg-config
              - clang
              - libclang-dev
              
              # --- Dépendances Xwayland-satellite (issues du Dockerfile) ---
              - xwayland
              - libxcb1
              - libxcb-cursor0
              - libxcb-cursor-dev
              - libegl1
              - libegl-dev # Ajouté pour les headers de compilation C/Rust
              
              # --- Utilitaires de l'environnement de bureau ---
              - xdg-desktop-portal
              - xdg-desktop-portal-wlr
              - grim
              - slurp
              - adwaita-icon-theme
              
      - name: install-noctalia # see https://docs.noctalia.dev/v4/getting-started/installation/#debian
        type: shell
        commands:
          - curl -fsSL https://pkg.noctalia.dev/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/noctalia.gpg
          - echo "deb [signed-by=/etc/apt/keyrings/noctalia.gpg] https://pkg.noctalia.dev/apt trixie main" | tee /etc/apt/sources.list.d/noctalia.list
          - apt update
          - apt install noctalia-shell
          

      - name: install-rust
        type: shell
        commands:
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          - . "$HOME/.cargo/env" && rustup toolchain install 1.88
          
      - name: build-driftwm
        type: shell
        commands:
          - . "$HOME/.cargo/env" && git clone https://github.com/malbiruk/driftwm.git && cd driftwm && make build && make install
          # Installation de xwayland-satellite depuis Git et placement dans un dossier global (/usr/local)
          - . "$HOME/.cargo/env" && cargo install --git https://github.com/Supreeeme/xwayland-satellite --root /usr/local
          
      - name: install-driftwm-session-file
        type: shell
        commands:
          - mkdir -p /usr/share/wayland-sessions
          - |
            cat <<EOF > /usr/share/wayland-sessions/driftwm.desktop
            [Desktop Entry]
            Name=driftwm
            Comment=DriftWM Wayland Compositor
            Exec=/usr/local/bin/driftwm
            Type=Application
            EOF

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock
          - rm -rf /root/.cargo
          - rm -rf /root/.rustup

      - name: fsguard
        type: fsguard
        CustomFsGuard: false
        FsGuardLocation: "/usr/sbin/FsGuard"
        GenerateKey: true
        FilelistPaths: ["/usr/bin"]
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
