name: Vanilla OS Driftwm
id: driftwm
vibversion: 1.0.7

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main
    addincludes: true
    singlelayer: false
    labels:
      maintainer: apoleon33
    args:
      DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive

    # Commands to run first before building the modules
    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Put your custom actions below this comment

      - name: install-dependencies
        type: includes
        includes:
          - modules/10-install-dependencies.yml
              

      - name: install-rust
        type: shell
        commands:
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          - . "$HOME/.cargo/env" && rustup toolchain install 1.88
          
      - name: build-driftwm
        type: shell
        commands:
          - . "$HOME/.cargo/env" && git clone https://github.com/malbiruk/driftwm.git && cd driftwm && make build && make install
          - . "$HOME/.cargo/env" && cargo install --git https://github.com/Supreeeme/xwayland-satellite --root /usr/local
          
      - name: install-driftwm-session-file
        type: shell
        commands:
          - mkdir -p /usr/share/wayland-sessions
          - |
            cat <<EOF > /usr/share/wayland-sessions/driftwm.desktop
            [Desktop Entry]
            Name=driftwm
            Comment=DriftWM Wayland Compositor
            Exec=/usr/local/bin/driftwm
            Type=Application
            EOF

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock
          - rm -rf /root/.cargo
          - rm -rf /root/.rustup

      - name: fsguard
        type: fsguard
        CustomFsGuard: false
        FsGuardLocation: "/usr/sbin/FsGuard"
        GenerateKey: true
        FilelistPaths: ["/usr/bin"]
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
